# Generated by Django 4.1.3 on 2022-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TxtFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='txt_files1/%Y/%m')),
                ('file2', models.FileField(upload_to='txt_files2/%Y/%m')),
                ('acc_f1', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_f2', models.CharField(blank=True, max_length=255, null=True)),
                ('results_f1', models.TextField(blank=True, null=True)),
                ('results_f2', models.TextField(blank=True, null=True)),
                ('img_f1', models.FileField(blank=True, null=True, upload_to='img_f1/%Y/%m')),
                ('img_f2', models.FileField(blank=True, null=True, upload_to='img_f2/%Y/%m')),
            ],
        ),
    ]
